object Versions {
    const val OKHTTP3 = "4.9.1"
    const val RETROFIT2 = "2.11.0"
    const val DATASTORE = "1.1.1"
    const val TED = "3.3.0"
    const val FIREBASE_CLOUD_FUNCTION = "20.4.0"
    const val GOOGLE_PLAY_SERVICE_AUTH = "21.1.0"
    const val FIREBASE_BOM = "32.8.1"
    const val GOOGLE_PLAY_SERVICE_LOCATION = "21.2.0"
    const val NAVER_MAP = "3.18.0"
    const val MATERIAL = "1.11.0"
    const val ESPRESSO = "3.5.1"
    const val JUNIT = "1.1.5"
    const val JUNIT_CORE = "4.13.2"
    const val CONSTRAINT_LAYOUT = "2.1.4"
    const val APPCOMPAT = "1.6.1"
    const val CORE_KTX = "1.12.0"
    const val NAVIGATION = "2.7.7"
    const val CREDENTIAL = "1.3.0-alpha03"
    const val GOOGLE_ID = "1.1.0"
    const val GLIDE = "4.15.1"
    
}